### PR TITLE
added comma on line 185, closed bracket on line 240

### PR DESCRIPTION
**Pull request by didierCH**
Hy Funk3
Nice game. When I wanted to run it had to correct to syntax-errors first. Here they are. :-)

### CODE REVIEW

**Comment by Funk3** [comment]
Thank you :)

**Comment by didierCH** [comment]
I thank you. My first successfull pull request! 👍

**Comment by Funk3** [comment]
My first merge :) If you want to add anything or help with the game by all means!

**Comment by didierCH** [comment]
Thank you.

**Pull request merged**
